version: '3.8'
volumes:
  postgres_data:

networks:
  backend_network:

services:
  postgres:
    image: postgres:14-alpine
    container_name: tech_store_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: tech_store_pgadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_network 